In [11]:
!pip install snscrape

Requirement already satisfied: snscrape in c:\users\admin\documents\custom office templates\lib\site-packages (0.4.3.20220106)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\documents\custom office templates\lib\site-packages (from snscrape) (4.11.1)
Requirement already satisfied: requests[socks] in c:\users\admin\documents\custom office templates\lib\site-packages (from snscrape) (2.27.1)
Requirement already satisfied: lxml in c:\users\admin\documents\custom office templates\lib\site-packages (from snscrape) (4.8.0)
Requirement already satisfied: filelock in c:\users\admin\documents\custom office templates\lib\site-packages (from snscrape) (3.6.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\documents\custom office templates\lib\site-packages (from beautifulsoup4->snscrape) (2.3.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\documents\custom office templates\lib\site-packages (from requests[socks]->snscrape) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\documents\custom office templates\lib\site-packages (from requests[socks]->snscrape) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\documents\custom office templates\lib\site-packages (from requests[socks]->snscrape) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\documents\custom office templates\lib\site-packages (from requests[socks]->snscrape) (1.26.9)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\admin\documents\custom office templates\lib\site-packages (from requests[socks]->snscrape) (1.7.1)

In [18]:
import pandas as pd
import snscrape.modules.twitter as sntwitter

In [23]:
query = "(#30DaysOfLearning OR #NG30DaysOfLearning) until:2022-07-07 since:2022-05-01"
tweets = []
limit = 30000


for tweet in sntwitter.TwitterHashtagScraper(query).get_items():
    
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.url, tweet.user.username, tweet.sourceLabel, tweet.user.location, tweet.content, tweet.likeCount, tweet.retweetCount,  tweet.quoteCount, tweet.replyCount])
        
df = pd.DataFrame(tweets, columns=['Date', 'TweetURL','User', 'Source', 'Location', 'Tweet', 'Likes_Count','Retweet_Count', 'Quote_Count', 'Reply_Count'])

df.to_csv('30DLTweets.csv')

In [24]:
df.head()

,Date,TweetURL,User,Source,Location,Tweet,Likes_Count,Retweet_Count,Quote_Count,Reply_Count
0,2022-07-06 22:10:43+00:00,https://twitter.com/Adebayo17108247/status/154...,Adebayo17108247,Twitter for Android,Lagos,Day 6 #30daysoflearning #100DaysOfCode \n\nSt...,9,6,0,1
1,2022-07-06 22:06:15+00:00,https://twitter.com/PJEnterprises3/status/1544...,PJEnterprises3,Twitter for Android,,https://t.co/kUyNt64A8W\nA dashboard I worked ...,0,0,0,0
2,2022-07-06 21:54:18+00:00,https://twitter.com/CoderOfPHCity/status/15448...,CoderOfPHCity,Twitter Web App,Port Harcourt,Day 3 of #30daysoflearning Reactjs.\n\nBuilt t...,4,1,0,0
3,2022-07-06 19:48:45+00:00,https://twitter.com/Moyin2_/status/15447703472...,Moyin2_,Twitter for Android,"Lagos, Nigeria",Day 8 of #100DaysOfCode \nDecided to take a br...,4,4,0,1
4,2022-07-06 18:23:19+00:00,https://twitter.com/TheOyinbooke/status/154474...,TheOyinbooke,Twitter for Android,Nigeria,Don't be in haste to share a screenshot of you...,52,8,1,3

In [25]:
df.describe()

       Likes_Count  Retweet_Count  Quote_Count  Reply_Count
count   986.000000     986.000000   986.000000   986.000000
mean     16.190669       3.596349     0.166329     1.191684
std      43.890937       9.510312     0.621707     2.880491
min       0.000000       0.000000     0.000000     0.000000
25%       1.000000       0.000000     0.000000     0.000000
50%       2.000000       0.000000     0.000000     0.000000
75%       9.000000       2.000000     0.000000     1.000000
max     613.000000     125.000000     8.000000    30.000000